export enum queryKeys {

    // partner
    LOGIN,
    GET_PARTNER_INFO,

    // services
    GET_SERVICES,
    GET_GLOBAL_SERVICES,
    CREATE_SERVICE,
    UPDATE_SERVICE,
    DELETE_SERVICE,

    //sub-services
    GET_SUB_SERVICES,
    CREATE_SUB_SERVICE,
    UPDATE_SUB_SERVICE,
    DELETE_SUB_SERVICE,

    // clinics
    GET_PARTNER_CLINICS,
    CREATE_CLINIC,
    UPDATE_CLINIC,
    DELETE_CLINIC,
    GET_SINGLE_CLINIC,

    // employee
    CREATE_EMPLOYEE,
    GET_EMPLOYEES,
    UPDATE_EMPLOYEE,
    DELETE_EMPLOYEE,

    //folder
    GET_FOLDERS,
    CREATE_FOLDER,
    UPDATE_FOLDER,
    DELETE_FOLDER,
    ASSIGN_EMPLOYEE,

    // working hours
    CREATE_WORKING_HOURS,
    UPDATE_WORKING_HOURS,
    DELETE_WORKING_HOURS,
    GET_WORKING_HOURS,
    GET_SINGLE_WORKING_HOURS,

    // reviews
    GET_REVIEWS,
    REPLY_TO_REVIEW,

    // bookings
    GET_BOOKINGS,
    CREATE_BOOKING,
    UPDATE_BOOKING,
    DELETE_BOOKING,

    // users
    GET_USERS
}